apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: elt-app
  name: etl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: etl-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etl-app
    spec:
      containers:
      - image: ghcr.io/surfriderfoundationeurope/etl:latest
        name: etl
        ports:
        - containerPort: 80
        env:
          - name: PGUSERNAME
            value: <pgusername>
          - name: PGDATABASE
            value: <pgdatabase>
          - name: PGSERVER
            value: <pgserver>
          - name: PGPWD
            value: <pgpwd>
          - name: CONN_STRING
            value: <conn_string>